import { Router } from 'express';
import { readFileSync, writeFileSync, existsSync, mkdirSync, chmodSync, renameSync, rmSync, symlinkSync } from 'fs';
import { dirname, join } from 'path';
import { execFile, spawn } from 'child_process';
import { promisify } from 'util';

const execFileP = promisify(execFile);
const router = Router();

const BACKUP_ENV_PATH = process.env.BACKUP_ENV_PATH || '/root/SyncNo/.backup.env';
const RCLONE_CONF_PATH = process.env.RCLONE_CONF_PATH || '/root/.config/rclone/rclone.conf';
const RESTIC_PASSWORD_FILE = process.env.RESTIC_PASSWORD_FILE || '/root/.restic-password';
const SYNCNO_ROOT = process.env.SYNCNO_ROOT || '/root/SyncNo';
const DB_SRC = process.env.SYNCNO_DB || join(SYNCNO_ROOT, 'backend/data/syncro.db');
const ATTACH_DIR = join(SYNCNO_ROOT, 'backend/data/attachments');
const STAGE_BASE = process.env.BACKUP_STAGE_DIR || '/mnt/backup-stage';
const RCLONE_REMOTE = 'sharepoint';
const MASK = '••••••••';

const JSON_ENTITIES = [
  'appointments', 'appointment_types', 'contacts', 'contracts', 'customers',
  'estimates', 'invoices', 'items', 'leads', 'payments', 'policy_folders',
  'portal_users', 'products', 'purchase_orders', 'schedules', 'syncro_users',
  'tickets', 'vendors', 'wiki_pages',
];
const JSON_API_PATH = { purchase_orders: 'purchase-orders' };

// Simple in-process lock so concurrent downloads don't blow the 3G tmpfs cap.
let downloadLock = false;
function withLock(res, fn) {
  if (downloadLock) {
    return res.status(409).json({ error: 'Another download in progress — wait and retry.' });
  }
  downloadLock = true;
  Promise.resolve()
    .then(fn)
    .catch(e => res.status(500).json({ error: e.message }))
    .finally(() => { downloadLock = false; });
}

function requireAdmin(req, res, next) {
  if (req.user?.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
  next();
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const m = line.match(/^export\s+([A-Z_][A-Z0-9_]*)\s*=\s*"?(.*?)"?\s*$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function parseRclone(text, remoteName) {
  const lines = text.split('\n');
  const out = {};
  let inSec = false;
  for (const line of lines) {
    const secMatch = line.match(/^\[(.+)\]$/);
    if (secMatch) { inSec = secMatch[1] === remoteName; continue; }
    if (!inSec) continue;
    const m = line.match(/^([a-z_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim();
  }
  return out;
}

function buildEnv(c) {
  const lines = [
    '# Generated by SyncNo settings UI. Do not edit by hand.',
    `export RESTIC_REPOSITORY="${(c.resticRepository || '').replace(/"/g, '')}"`,
  ];
  // Prefer inline password (UI supplies it). Fall back to password file otherwise.
  if (c.resticPassword) {
    lines.push(`export RESTIC_PASSWORD="${c.resticPassword.replace(/"/g, '')}"`);
  } else {
    lines.push(`export RESTIC_PASSWORD_FILE="${RESTIC_PASSWORD_FILE}"`);
  }
  lines.push(`export RCLONE_CONFIG="${RCLONE_CONF_PATH}"`);
  lines.push(`export BACKUP_KEEP_DAILY="${String(c.keepDaily || 14)}"`);
  lines.push(`export BACKUP_STAGE_DIR="${(c.stageDir || '/mnt/backup-stage').replace(/"/g, '')}"`);
  if (c.rcloneTransfers) lines.push(`export RCLONE_TRANSFERS="${String(c.rcloneTransfers).replace(/"/g, '')}"`);
  if (c.rcloneTpslimit) lines.push(`export RCLONE_TPSLIMIT="${String(c.rcloneTpslimit).replace(/"/g, '')}"`);
  return lines.join('\n') + '\n';
}

function buildRcloneConf(c) {
  return [
    `[${RCLONE_REMOTE}]`,
    'type = onedrive',
    `client_id = ${(c.clientId || '').trim()}`,
    `client_secret = ${(c.clientSecret || '').trim()}`,
    `tenant = ${(c.tenantId || '').trim()}`,
    'drive_type = documentLibrary',
    '',
  ].join('\n');
}

function writeFileSecure(path, text) {
  mkdirSync(dirname(path), { recursive: true });
  // Write atomically via temp then rename, then enforce mode
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, text);
  chmodSync(tmp, 0o600);
  renameSync(tmp, path);
}

// GET /api/backup-settings — return current config. Secrets masked unless ?reveal=1
router.get('/', requireAdmin, (req, res) => {
  const reveal = req.query.reveal === '1';
  const result = { env: {}, rclone: {}, envExists: false, rcloneExists: false, passwordFileExists: false };

  if (existsSync(BACKUP_ENV_PATH)) {
    result.envExists = true;
    const env = parseEnv(readFileSync(BACKUP_ENV_PATH, 'utf8'));
    result.env = {
      resticRepository: env.RESTIC_REPOSITORY || '',
      resticPassword: env.RESTIC_PASSWORD || '',
      resticPasswordFile: env.RESTIC_PASSWORD_FILE || '',
      rcloneConfig: env.RCLONE_CONFIG || RCLONE_CONF_PATH,
      keepDaily: env.BACKUP_KEEP_DAILY || '14',
      stageDir: env.BACKUP_STAGE_DIR || '/mnt/backup-stage',
      rcloneTransfers: env.RCLONE_TRANSFERS || '',
      rcloneTpslimit: env.RCLONE_TPSLIMIT || '',
    };
  }
  if (existsSync(RCLONE_CONF_PATH)) {
    result.rcloneExists = true;
    const rc = parseRclone(readFileSync(RCLONE_CONF_PATH, 'utf8'), RCLONE_REMOTE);
    result.rclone = {
      clientId: rc.client_id || '',
      clientSecret: rc.client_secret || '',
      tenantId: rc.tenant || '',
    };
  }
  result.passwordFileExists = existsSync(RESTIC_PASSWORD_FILE);

  if (!reveal) {
    if (result.env.resticPassword) result.env.resticPassword = MASK;
    if (result.rclone.clientSecret) result.rclone.clientSecret = MASK;
  }
  res.json(result);
});

// POST /api/backup-settings — write env file + rclone.conf + password file
router.post('/', requireAdmin, (req, res) => {
  const body = req.body || {};
  try {
    const envConfig = body.env || {};
    const rcloneConfig = body.rclone || {};

    if (Object.keys(envConfig).length > 0) {
      // Merge with existing if client sent partial config (e.g. only changed one field)
      let merged = envConfig;
      if (existsSync(BACKUP_ENV_PATH)) {
        const existing = parseEnv(readFileSync(BACKUP_ENV_PATH, 'utf8'));
        const existingDecoded = {
          resticRepository: existing.RESTIC_REPOSITORY || '',
          resticPassword: existing.RESTIC_PASSWORD || '',
          resticPasswordFile: existing.RESTIC_PASSWORD_FILE || '',
          rcloneConfig: existing.RCLONE_CONFIG || RCLONE_CONF_PATH,
          keepDaily: existing.BACKUP_KEEP_DAILY || '14',
          stageDir: existing.BACKUP_STAGE_DIR || '/mnt/backup-stage',
          rcloneTransfers: existing.RCLONE_TRANSFERS || '',
          rcloneTpslimit: existing.RCLONE_TPSLIMIT || '',
        };
        merged = { ...existingDecoded, ...envConfig };
        // Mask still equals MASK? Preserve existing real value (need reveal to load it).
        // Caller is responsible for sending real values; if MASK received, we keep existing.
        if (envConfig.resticPassword === MASK) merged.resticPassword = existingDecoded.resticPassword;
        else if (!envConfig.resticPassword) delete merged.resticPassword;
      }
      writeFileSecure(BACKUP_ENV_PATH, buildEnv(merged));

      // Persist password to file too (for scripts that prefer RESTIC_PASSWORD_FILE)
      if (merged.resticPassword) {
        writeFileSecure(RESTIC_PASSWORD_FILE, `${merged.resticPassword}\n`);
      }
    }

    if (Object.keys(rcloneConfig).length > 0) {
      let merged = rcloneConfig;
      if (existsSync(RCLONE_CONF_PATH)) {
        const existing = parseRclone(readFileSync(RCLONE_CONF_PATH, 'utf8'), RCLONE_REMOTE);
        const existingDecoded = {
          clientId: existing.client_id || '',
          clientSecret: existing.client_secret || '',
          tenantId: existing.tenant || '',
        };
        merged = { ...existingDecoded, ...rcloneConfig };
        if (rcloneConfig.clientSecret === MASK) merged.clientSecret = existingDecoded.clientSecret;
      }
      writeFileSecure(RCLONE_CONF_PATH, buildRcloneConf(merged));
    }

    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// POST /api/backup-settings/test — run rclone lsd sharepoint:
router.post('/test', requireAdmin, async (req, res) => {
  try {
    const env = { ...process.env, RCLONE_CONFIG: RCLONE_CONF_PATH };
    const { stdout, stderr } = await execFileP('rclone', ['lsd', `${RCLONE_REMOTE}:`], {
      env, timeout: 30000,
    });
    res.json({ ok: true, output: (stdout || '') + (stderr ? `\n[stderr]\n${stderr}` : '') });
  } catch (e) {
    res.status(200).json({
      ok: false,
      output: (e.stdout || '') + (e.stderr ? `\n[stderr]\n${e.stderr}` : ''),
      error: e.message,
    });
  }
});

// POST /api/backup-settings/init — restic init
router.post('/init', requireAdmin, async (req, res) => {
  try {
    if (!existsSync(BACKUP_ENV_PATH)) return res.status(400).json({ error: '.backup.env missing — save config first' });
    const env = parseEnv(readFileSync(BACKUP_ENV_PATH, 'utf8'));
    const execEnv = { ...process.env, ...env, RCLONE_CONFIG: RCLONE_CONF_PATH };
    if (!execEnv.RESTIC_REPOSITORY) return res.status(400).json({ error: 'RESTIC_REPOSITORY not set' });
    if (!execEnv.RESTIC_PASSWORD && !execEnv.RESTIC_PASSWORD_FILE) {
      return res.status(400).json({ error: 'RESTIC_PASSWORD not set' });
    }
    const args = ['-r', execEnv.RESTIC_REPOSITORY, 'init'];
    if (execEnv.RESTIC_PASSWORD_FILE) args.push('--password-file', execEnv.RESTIC_PASSWORD_FILE);
    const { stdout, stderr } = await execFileP('restic', args, { env: execEnv, timeout: 60000 });
    res.json({ ok: true, output: (stdout || '') + (stderr ? `\n[stderr]\n${stderr}` : '') });
  } catch (e) {
    res.status(200).json({
      ok: false,
      output: (e.stdout || '') + (e.stderr ? `\n[stderr]\n${e.stderr}` : ''),
      error: e.message,
    });
  }
});

// POST /api/backup-settings/run — trigger systemd backup service now
router.post('/run', requireAdmin, async (req, res) => {
  try {
    await execFileP('systemctl', ['start', 'syncno-backup.service'], { timeout: 10000 });
    res.json({ ok: true, message: 'Backup triggered. Check journalctl -u syncno-backup.service' });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

// POST /api/backup-settings/enable-timer
router.post('/enable-timer', requireAdmin, async (req, res) => {
  try {
    await execFileP('systemctl', ['enable', '--now', 'syncno-backup.timer'], { timeout: 10000 });
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

// GET /api/backup-settings/status — timer + last backup
router.get('/status', requireAdmin, async (req, res) => {
  try {
    const timer = await execFileP('systemctl', ['is-enabled', 'syncno-backup.timer'], { timeout: 5000 }).then(r => r.stdout.trim()).catch(() => 'unknown');
    const active = await execFileP('systemctl', ['is-active', 'syncno-backup.timer'], { timeout: 5000 }).then(r => r.stdout.trim()).catch(() => 'unknown');
    const next = await execFileP('systemctl', ['list-timers', 'syncno-backup.timer', '--no-pager', '--output=json'], { timeout: 5000 }).then(r => JSON.parse(r.stdout)).catch(() => null);
    res.json({
      timerEnabled: timer === 'enabled',
      timerActive: active === 'active',
      nextRun: next?.[0]?.next_at || null,
    });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ─── Download endpoints ──────────────────────────────────────────────────────
// Browser downloads. Stream tar.gz so we don't need disk for the whole archive
// (tmpfs is only 3G, full backup snapshot alone is ~2.9G).

function ts() {
  return new Date().toISOString().replace(/[-:]/g, '').replace(/\..*/, '');
}

async function fetchAllPages(entity, apiKey) {
  const path = JSON_API_PATH[entity] || entity;
  const base = `http://localhost:${process.env.PORT || 3002}/api/${path}`;
  let page = 1;
  let merged = [];
  while (true) {
    const url = `${base}?page=${page}&limit=1000`;
    const r = await fetch(url, { headers: { Authorization: `Bearer ${apiKey}` } });
    if (!r.ok) throw new Error(`${entity} HTTP ${r.status}`);
    const d = await r.json();
    const data = Array.isArray(d) ? d : (d.data || []);
    merged = merged.concat(data);
    if (data.length < 1000) break;
    page++;
    if (page > 10000) break;
  }
  return merged;
}

// GET /api/backup-settings/download-json — tar.gz of every entity's JSON.
// Stages JSON files in tmpfs, tars streaming, deletes after.
router.get('/download-json', requireAdmin, (req, res) => {
  withLock(res, async () => {
    const stamp = ts();
    const stage = join(STAGE_BASE, `json-${stamp}`);
    mkdirSync(stage, { recursive: true });
    try {
      const apiKey = process.env.SYNCNO_API_KEY;
      if (!apiKey) throw new Error('SYNCNO_API_KEY not set');
      for (const entity of JSON_ENTITIES) {
        const data = await fetchAllPages(entity, apiKey);
        const body = JSON.stringify({
          entity, exported_at: new Date().toISOString(), count: data.length, data,
        }, null, 2);
        writeFileSync(join(stage, `${entity}.json`), body);
      }
      res.setHeader('Content-Type', 'application/gzip');
      res.setHeader('Content-Disposition', `attachment; filename="syncno-json-${stamp}.tar.gz"`);
      const tar = spawn('tar', ['czf', '-', '-C', stage, '.']);
      tar.stdout.pipe(res);
      tar.stderr.on('data', d => console.error('[tar/json]', d.toString()));
      await new Promise((resolve, reject) => {
        tar.on('close', code => code === 0 ? resolve() : reject(new Error(`tar exited ${code}`)));
        tar.on('error', reject);
      });
    } finally {
      rmSync(stage, { recursive: true, force: true });
    }
  });
});

// GET /api/backup-settings/download — full backup tar.gz (DB + attachments + env files).
// Stages a consistent SQLite snapshot in tmpfs, tars streaming with -h (follows
// symlinks for attachments + env files), deletes after.
router.get('/download', requireAdmin, (req, res) => {
  withLock(res, async () => {
    const stamp = ts();
    const stage = join(STAGE_BASE, `full-${stamp}`);
    mkdirSync(stage, { recursive: true });
    const snapPath = join(stage, 'syncro.db');
    try {
      if (!existsSync(DB_SRC)) throw new Error(`DB not found at ${DB_SRC}`);
      // Consistent SQLite snapshot (online backup API).
      await new Promise((resolve, reject) => {
        const s = spawn('sqlite3', [DB_SRC, `.backup '${snapPath}'`]);
        let err = '';
        s.stderr.on('data', d => { err += d.toString(); });
        s.on('close', code => code === 0 ? resolve() : reject(new Error(`sqlite3 backup exited ${code}: ${err}`)));
        s.on('error', reject);
      });

      // Integrity-check the snapshot before serving.
      const integrity = await new Promise((resolve, reject) => {
        const s = spawn('sqlite3', [snapPath, 'PRAGMA integrity_check;']);
        let out = '';
        s.stdout.on('data', d => { out += d.toString(); });
        s.on('close', code => code === 0 ? resolve(out.trim()) : reject(new Error(`integrity_check exited ${code}`)));
        s.on('error', reject);
      });
      if (integrity !== 'ok') throw new Error(`snapshot integrity check failed: ${integrity}`);

      mkdirSync(join(stage, 'env'), { recursive: true });
      const envLinks = [
        [join(SYNCNO_ROOT, '.env'), 'root.env'],
        [join(SYNCNO_ROOT, 'backend/.env'), 'backend.env'],
        [join(SYNCNO_ROOT, 'frontend/.env'), 'frontend.env'],
        [join(SYNCNO_ROOT, 'frontend/.env.local'), 'frontend.env.local'],
      ];
      for (const [src, name] of envLinks) {
        if (existsSync(src)) symlinkSync(src, join(stage, 'env', name));
      }
      symlinkSync(ATTACH_DIR, join(stage, 'attachments'));

      res.setHeader('Content-Type', 'application/gzip');
      res.setHeader('Content-Disposition', `attachment; filename="syncno-backup-${stamp}.tar.gz"`);
      const tar = spawn('tar', ['czhf', '-', '-C', stage, '.']);
      tar.stdout.pipe(res);
      tar.stderr.on('data', d => console.error('[tar/full]', d.toString()));
      await new Promise((resolve, reject) => {
        tar.on('close', code => code === 0 ? resolve() : reject(new Error(`tar exited ${code}`)));
        tar.on('error', reject);
      });
    } finally {
      rmSync(stage, { recursive: true, force: true });
    }
  });
});

export default router;
